services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
      args:
        API_BASE_URL: ${API_BASE_URL}
    container_name: pole-front-nginx
    env_file:
      - .env
      - path: .env.dev
        required: false
    ports:
      - "80:80"
    restart: unless-stopped
