server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # -------------------------------------------------------
    # PROXY — API Symfony
    # Le navigateur appelle /api/... → Nginx transfère au back
    # Connexion HTTP interne (SSL géré par OpenResty de l'école)
    # On passe le bon Host header pour que le back pose le cookie
    # sur le bon domaine (std34.beaupeyrat.com)
    # -------------------------------------------------------
    location /api/ {
        proxy_pass         http://10.187.22.33/api/;

        proxy_set_header   Host              std33.beaupeyrat.com;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto https;
    }

    # -------------------------------------------------------
    # PROXY — Medias Vich exposes en /media/*
    # (logos clubs, tutos skills, etc.)
    # -------------------------------------------------------
    location /media/ {
        proxy_pass       http://10.187.22.33/media/;
        proxy_set_header Host std33.beaupeyrat.com;
    }

    # -------------------------------------------------------
    # COMPAT — anciens chemins /public/media/*
    # On les route vers /media cote back
    # -------------------------------------------------------
    location /public/media/ {
        proxy_pass       http://10.187.22.33/media/;
        proxy_set_header Host std33.beaupeyrat.com;
    }
    

    # -------------------------------------------------------
    # Cache long pour les assets Angular compilés
    # -------------------------------------------------------
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml image/svg+xml;
    
    # Cache des assets statiques (JS, CSS, images)
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # -------------------------------------------------------
    # SPA routing — toutes les routes Angular → index.html
    # -------------------------------------------------------
    location / {
        try_files $uri $uri/ /index.html;
    }
}